In [1]:
# Importar librerías necesarias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn import datasets
from io import StringIO
from sklearn.tree import export_graphviz
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn import metrics
%matplotlib inline

In [28]:
# Con un simple IRPF = pd.read_csv('IRPFmunicipios.csv') ya me lo leía bien pero he hecho la prueba al no entender 
#  bien lo que leía y he añanadido los attributos de encoding y separación 

IRPF = pd.read_csv('IRPFmunicipios.csv', encoding='utf-8', sep=',')

In [16]:
IRPF

MUNI_1     MUNI_2  MUNI_3     MUNI_4        MUNI_7        MUNI_8  \
0       816913.0   905175.0     1.0  1602386.0  2.023095e+10  1.751150e+09   
1       822605.0   908603.0     1.0  1604555.0  2.040319e+10  1.576207e+09   
2       823406.0   907030.0     1.0  1608746.0  2.102946e+10  1.565046e+09   
3       825322.0   906459.0     1.0  1620809.0  2.182936e+10  1.581185e+09   
4      1602358.0  1803521.0     1.0  3165235.0  4.364551e+10  3.043913e+09   
...          ...        ...     ...        ...           ...           ...   
14947   378106.0   432247.0     1.0   791413.0  8.616336e+09  3.791193e+08   
14948   293333.0   345489.0     1.0   688711.0  6.708794e+09  1.979152e+08   
14949   225862.0   267216.0     1.0   571026.0  4.583663e+09  1.056567e+08   
14950  1681207.0  1859532.0     1.0  3223334.0  4.895921e+10  3.178230e+09   
14951   837111.0   915106.0     1.0  1620343.0  2.273393e+10  1.506161e+09   

             MUNI_9       MUNI_10      MUNI_11       MUNI_12  ...  \
0      1.469940e+09  1.668121e+09   7147695.25  8.389411e+08  ...   
1      1.503760e+09  1.809805e+09   5145109.40  1.156989e+09  ...   
2      1.598920e+09  2.071491e+09   2655852.85  1.342493e+09  ...   
3      1.706492e+09  2.195776e+09   2463190.36  1.538679e+09  ...   
4      2.243229e+09  2.567423e+09  12847106.45  1.680382e+09  ...   
...             ...           ...          ...           ...  ...   
14947  5.032196e+08  7.833208e+08    356511.26  5.254405e+08  ...   
14948  3.218270e+08  5.684984e+08    550103.80  3.218944e+08  ...   
14949  2.402960e+08  4.150182e+08    328531.82  2.035981e+08  ...   
14950  2.863382e+09  3.878467e+09   5610473.37  3.739553e+09  ...   
14951  1.830285e+09  2.320791e+09   4356734.97  1.878452e+09  ...   

           MUNI_179   MUNI_180      MUNI_181      MUNI_182  MUNI_183  \
0      1.942422e+10   788090.0  4.563544e+09  5.843212e+08  250157.0   
1      1.974831e+10   794316.0  4.594353e+09  5.873386e+08  252786.0   
2      2.086548e+10   781565.0  5.024814e+09  7.602769e+08  256098.0   
3      2.178682e+10   787234.0  5.033399e+09  7.672366e+08  259640.0   
4      4.082693e+10  1549349.0  8.915536e+09  1.232230e+09  508249.0   
...             ...        ...           ...           ...       ...   
14947  8.314278e+09   356331.0  2.290147e+09  4.030725e+08  132576.0   
14948  6.387854e+09   275601.0  1.757701e+09  3.754732e+08  114660.0   
14949  4.278383e+09   211849.0  1.339049e+09  3.085669e+08   93740.0   
14950  4.785001e+10  1618023.0  1.019803e+10  1.630753e+09  535364.0   
14951  2.283766e+10   803939.0  5.095630e+09  7.786475e+08  265245.0   

           MUNI_184   MUNI_185  TRAMO  MUNI_DEF  EJER  
0      5.605529e+09   816907.0      1       880  2013  
1      5.653749e+09   822588.0      1       880  2014  
2      6.439762e+09   823406.0      1       880  2015  
3      6.480901e+09   825322.0      1       880  2016  
4      1.077706e+10  1602342.0      1      4356  2013  
...             ...        ...    ...       ...   ...  
14947  2.967814e+09   378106.0      1      7221  2017  
14948  2.308399e+09   293333.0      1      6150  2017  
14949  1.842531e+09   225862.0      1      4524  2017  
14950  1.275543e+10  1681207.0      1      4356  2017  
14951  6.585832e+09   837111.0      1       880  2017  

[14952 rows x 115 columns]

In [6]:
IRPF.describe()

MUNI_1        MUNI_2        MUNI_3        MUNI_4        MUNI_7  \
count  1.488200e+04  1.488200e+04  14882.000000  1.488200e+04  1.488200e+04   
mean   6.556759e+03  7.714944e+03      2.550060  1.471877e+04  1.336854e+08   
std    3.780311e+04  4.254550e+04     16.958266  7.551751e+04  1.003504e+09   
min    1.850000e+02  2.220000e+02      1.000000  0.000000e+00  2.070768e+06   
25%    7.950000e+02  9.660000e+02      1.000000  1.855250e+03  1.116598e+07   
50%    1.600500e+03  1.934500e+03      1.000000  3.694000e+03  2.470335e+07   
75%    4.256750e+03  5.107000e+03      1.000000  9.837500e+03  7.475580e+07   
max    1.681207e+06  1.859532e+06    345.000000  3.223334e+06  4.895921e+10   

             MUNI_8        MUNI_9       MUNI_10       MUNI_11       MUNI_12  \
count  1.488200e+04  1.488200e+04  1.488200e+04  1.488200e+04  1.488200e+04   
mean   5.691561e+06  6.171124e+06  1.085227e+07  1.778168e+04  4.445276e+06   
std    6.566990e+07  5.746097e+07  7.571274e+07  2.032316e+05  5.815823e+07   
min    9.161120e+03  4.546730e+03  1.069445e+05  0.000000e+00  1.835900e+03   
25%    3.169027e+05  2.861741e+05  1.329340e+06  0.000000e+00  1.915426e+05   
50%    7.618323e+05  7.854408e+05  2.728237e+06  1.056000e+03  4.736551e+05   
75%    2.366274e+06  2.817988e+06  6.876883e+06  5.524110e+03  1.633270e+06   
max    3.295191e+09  2.863382e+09  3.878467e+09  1.284711e+07  3.739553e+09   

       ...      MUNI_179      MUNI_180      MUNI_181      MUNI_182  \
count  ...  1.488200e+04  1.488200e+04  1.488200e+04  1.488200e+04   
mean   ...  1.229609e+08  6.212322e+03  3.800509e+07  7.316967e+06   
std    ...  9.620639e+08  3.621660e+04  2.219566e+08  3.536355e+07   
min    ...  1.711085e+06  1.800000e+02  9.989370e+05  8.109000e+04   
25%    ...  9.817684e+06  7.440000e+02  4.673588e+06  7.849000e+05   
50%    ...  2.185466e+07  1.510000e+03  9.341440e+06  1.808675e+06   
75%    ...  6.698235e+07  4.019750e+03  2.445588e+07  5.130374e+06   
max    ...  4.785001e+10  1.618023e+06  1.019803e+10  1.630753e+09   

            MUNI_183      MUNI_184      MUNI_185         TRAMO      MUNI_DEF  \
count   14882.000000  1.488200e+04  1.488200e+04  14952.000000  14952.000000   
mean     2551.926220  4.894362e+07  6.556744e+03      6.213349   3857.290663   
std     12479.530648  2.779023e+08  3.780300e+04      1.331472   2350.881958   
min        28.000000  1.265466e+06  1.850000e+02      1.000000      4.000000   
25%       277.000000  5.910287e+06  7.950000e+02      6.000000   1873.000000   
50%       626.000000  1.196562e+07  1.600500e+03      7.000000   3861.000000   
75%      1779.000000  3.191788e+07  4.256750e+03      7.000000   5809.000000   
max    535364.000000  1.275543e+10  1.681207e+06     10.000000   9168.000000   

               EJER  
count  14952.000000  
mean    2014.987694  
std        1.413924  
min     2013.000000  
25%     2014.000000  
50%     2015.000000  
75%     2016.000000  
max     2017.000000  

[8 rows x 115 columns]

In [8]:
IRPF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14952 entries, 0 to 14951
Columns: 115 entries, MUNI_1 to EJER
dtypes: float64(112), int64(3)
memory usage: 13.1 MB


In [9]:
IRPF.columns

Index(['MUNI_1', 'MUNI_2', 'MUNI_3', 'MUNI_4', 'MUNI_7', 'MUNI_8', 'MUNI_9',
       'MUNI_10', 'MUNI_11', 'MUNI_12',
       ...
       'MUNI_179', 'MUNI_180', 'MUNI_181', 'MUNI_182', 'MUNI_183', 'MUNI_184',
       'MUNI_185', 'TRAMO', 'MUNI_DEF', 'EJER'],
      dtype='object', length=115)

In [17]:
IRPF['TRAMO']

0        1
1        1
2        1
3        1
4        1
        ..
14947    1
14948    1
14949    1
14950    1
14951    1
Name: TRAMO, Length: 14952, dtype: int64

In [19]:
IRPF['TRAMO'].unique()

array([ 1,  2,  3,  4,  5,  6,  7, 10], dtype=int64)

In [20]:
IRPF['MUNI_DEF']

0         880
1         880
2         880
3         880
4        4356
         ... 
14947    7221
14948    6150
14949    4524
14950    4356
14951     880
Name: MUNI_DEF, Length: 14952, dtype: int64

In [21]:
IRPF['MUNI_DEF'].unique()

array([ 880, 4356, 4524, ..., 3087, 2468,  347], dtype=int64)

In [22]:
IRPF['EJER']

0        2013
1        2014
2        2015
3        2016
4        2013
         ... 
14947    2017
14948    2017
14949    2017
14950    2017
14951    2017
Name: EJER, Length: 14952, dtype: int64

In [23]:
IRPF['EJER'].unique()

array([2013, 2014, 2015, 2016, 2017], dtype=int64)

In [29]:
# Vemos que la columna de Ejercicio hace referencia al año, como solo nos interesa el 2017, vamos a reducir el DF a
#  ese año 

IRPF[IRPF['EJER']=='2017']

Empty DataFrame
Columns: [MUNI_1, MUNI_2, MUNI_3, MUNI_4, MUNI_7, MUNI_8, MUNI_9, MUNI_10, MUNI_11, MUNI_12, MUNI_13, MUNI_14, MUNI_15, MUNI_16, MUNI_17, MUNI_18, MUNI_19, MUNI_23, MUNI_24, MUNI_25, MUNI_26, MUNI_27, MUNI_28, MUNI_29, MUNI_30, MUNI_31, MUNI_32, MUNI_56, MUNI_57, MUNI_58, MUNI_59, MUNI_62, MUNI_63, MUNI_64, MUNI_65, MUNI_66, MUNI_67, MUNI_68, MUNI_69, MUNI_70, MUNI_71, MUNI_72, MUNI_73, MUNI_74, MUNI_75, MUNI_80, MUNI_81, MUNI_82, MUNI_83, MUNI_86, MUNI_87, MUNI_88, MUNI_89, MUNI_90, MUNI_91, MUNI_92, MUNI_93, MUNI_94, MUNI_95, MUNI_122, MUNI_123, MUNI_124, MUNI_125, MUNI_126, MUNI_127, MUNI_128, MUNI_129, MUNI_130, MUNI_131, MUNI_132, MUNI_133, MUNI_136, MUNI_137, MUNI_138, MUNI_139, MUNI_140, MUNI_141, MUNI_142, MUNI_143, MUNI_144, MUNI_145, MUNI_146, MUNI_147, MUNI_148, MUNI_149, MUNI_150, MUNI_151, MUNI_152, MUNI_153, MUNI_154, MUNI_155, MUNI_156, MUNI_157, MUNI_158, MUNI_159, MUNI_160, MUNI_161, MUNI_164, MUNI_165, MUNI_168, ...]
Index: []

[0 rows x 115 columns]

In [34]:
# No puede ser que no hay ni una sola columna que en ejercicio tenga el valor de '2017' 
#  ya que hemos visto que era un valor único de esa columna. 

# Vamos a ver las filas que tienen '2017' en la columna de EJER:

IRPF['EJER'].value_counts()

2013    3024
2014    3012
2015    2994
2016    2968
2017    2954
Name: EJER, dtype: int64

In [35]:
# Deberia salir una dimensión de 2954x115 
# Vemos que el dtype es int64, probemos a ponerlo como número y no como texto (sin comillas):

IRPF[IRPF['EJER']==2017]

MUNI_1     MUNI_2  MUNI_3     MUNI_4        MUNI_7        MUNI_8  \
11998    24703.0    29616.0   235.0    56121.0  3.382131e+08  9.065668e+06   
11999    27121.0    34056.0   231.0    66019.0  3.181148e+08  1.133643e+07   
12000    15718.0    19553.0   183.0    38015.0  2.024246e+08  1.152541e+07   
12001    18820.0    22274.0    83.0    37716.0  2.812936e+08  6.632486e+06   
12002    16869.0    21427.0    90.0    41704.0  2.389209e+08  3.564319e+06   
...          ...        ...     ...        ...           ...           ...   
14947   378106.0   432247.0     1.0   791413.0  8.616336e+09  3.791193e+08   
14948   293333.0   345489.0     1.0   688711.0  6.708794e+09  1.979152e+08   
14949   225862.0   267216.0     1.0   571026.0  4.583663e+09  1.056567e+08   
14950  1681207.0  1859532.0     1.0  3223334.0  4.895921e+10  3.178230e+09   
14951   837111.0   915106.0     1.0  1620343.0  2.273393e+10  1.506161e+09   

             MUNI_9       MUNI_10     MUNI_11       MUNI_12  ...  \
11998  1.159749e+07  5.055889e+07     2156.60  9.757626e+06  ...   
11999  9.875271e+06  5.582630e+07     1000.00  9.736124e+06  ...   
12000  1.045199e+07  4.659275e+07     1200.00  9.622682e+06  ...   
12001  7.222770e+06  3.005897e+07     9460.69  5.544261e+06  ...   
12002  7.079041e+06  2.796795e+07     1440.00  5.446324e+06  ...   
...             ...           ...         ...           ...  ...   
14947  5.032196e+08  7.833208e+08   356511.26  5.254405e+08  ...   
14948  3.218270e+08  5.684984e+08   550103.80  3.218944e+08  ...   
14949  2.402960e+08  4.150182e+08   328531.82  2.035981e+08  ...   
14950  2.863382e+09  3.878467e+09  5610473.37  3.739553e+09  ...   
14951  1.830285e+09  2.320791e+09  4356734.97  1.878452e+09  ...   

           MUNI_179   MUNI_180      MUNI_181      MUNI_182  MUNI_183  \
11998  2.992982e+08    23369.0  1.599984e+08  1.855438e+07    6220.0   
11999  2.781423e+08    25523.0  1.778004e+08  1.744368e+07    5754.0   
12000  1.990650e+08    14830.0  1.002304e+08  1.150270e+07    3789.0   
12001  2.417664e+08    17551.0  1.159432e+08  1.938946e+07    6613.0   
12002  2.049498e+08    15665.0  1.065050e+08  1.824802e+07    5396.0   
...             ...        ...           ...           ...       ...   
14947  8.314278e+09   356331.0  2.290147e+09  4.030725e+08  132576.0   
14948  6.387854e+09   275601.0  1.757701e+09  3.754732e+08  114660.0   
14949  4.278383e+09   211849.0  1.339049e+09  3.085669e+08   93740.0   
14950  4.785001e+10  1618023.0  1.019803e+10  1.630753e+09  535364.0   
14951  2.283766e+10   803939.0  5.095630e+09  7.786475e+08  265245.0   

           MUNI_184   MUNI_185  TRAMO  MUNI_DEF  EJER  
11998  1.947094e+08    24703.0     10      8168  2017  
11999  2.181681e+08    27121.0     10      8167  2017  
12000  1.225762e+08    15718.0     10      8165  2017  
12001  1.488894e+08    18820.0     10      8164  2017  
12002  1.369275e+08    16869.0     10      8163  2017  
...             ...        ...    ...       ...   ...  
14947  2.967814e+09   378106.0      1      7221  2017  
14948  2.308399e+09   293333.0      1      6150  2017  
14949  1.842531e+09   225862.0      1      4524  2017  
14950  1.275543e+10  1681207.0      1      4356  2017  
14951  6.585832e+09   837111.0      1       880  2017  

[2954 rows x 115 columns]

In [36]:
# Una vez comprobamos que es lo que queriamos (reducir el DF al ejercicio de 2017), sobreescribimos el DF

IRPF = IRPF[IRPF['EJER']==2017]

In [37]:
# Y comprobamos los valores únicos:

IRPF['EJER'].unique()

array([2017], dtype=int64)

In [38]:
# Ahora faltaria averiguar a qué hace referencia TRAMO y MUNI_DEF, ¡probemos cosas! 

IRPF['TRAMO'].value_counts()

7     1702
6      507
5      318
4      244
3       80
2       52
10      45
1        6
Name: TRAMO, dtype: int64

In [ ]:
# Hasta donde yo sé el IRPF tiene 5 tramos, aquí hay doble, ¿no hará referencia al tramo impositivo?
## entonces, ¿qué puede ser esa variable?

In [39]:
IRPF['MUNI_DEF'].value_counts()

6143    1
4403    1
7429    1
7425    1
3327    1
       ..
679     1
6822    1
156     1
2724    1
4096    1
Name: MUNI_DEF, Length: 2954, dtype: int64

In [ ]:
# Si solo hay una variable por cada MUNI_DEF podría ser una KP para cruzar con el maestro de municipios

In [41]:
#Guardo el csv procesado (me he quedado únicamente con el ejercicio 2017):

IRPF.to_csv('IRPF_2017.csv')